# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
# in dev
version=1.5.51
group=org.dawnoftime.dawnoftime
java_version=25

# Common
minecraft_version=26.1.2
mod_name=Dawn Of Time
mod_author=Poulpinou & TheGoldenWorld
mod_id=dawnoftimebuilder
license=MIT
credits=Mr_Ch0c0late1, Instantnootles, Aythya, Knoxxturre, Grand_Gibus, Lucthar, Botmark, Wonyu, Seynax, and the whole DoT team.
description=This mod adds many blocks and items from different cultures.
minecraft_version_range=[26.1.2, 26.2)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started for new versions
parchment_minecraft=26.1.2
parchment_version=2026.01.14

# Fabric
fabric_version=0.146.1+26.1.2
fabric_loader_version=0.16.15
modmenu_version=14.0.0+beta.3

# Forge
forge_version=52.0.0
forge_loader_version_range=[52,)

# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
